blogApp/posts/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from blogApp.posts import views

urlpatterns = patterns(
    '',
    url(r'^$', views.MainPage.as_view(), {}, name='main_page'),
    url(r'^(?P<post_slug>[^/]+)$', views.ShowPost.as_view(), {}, name='show_post'),
    url(r'^admin/preview/(?P<post_key>[^/]+)$', views.PreviewPost.as_view(), {}, name='preview_post'),
    url(r'^admin/add$', views.NewPost.as_view(), {}, name='new_post'),
    url(r'^admin/dashboard$', views.PostDashboard.as_view(), {}, name='post_dashboard'),
    url(r'^admin/edit/(?P<post_key>[^/]+)$', views.EditPost.as_view(), {}, name='edit_post'),
    url(r'^admin/delete/(?P<post_key>[^/]+)$', views.delete_post, {}, name='delete_post'),

)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^500/$', 'django.views.generic.simple.direct_to_template', {'template': '500.html'}),
        url(r'^404/$', 'django.views.generic.simple.direct_to_template', {'template': '404.html'}),
        )

blogApp/users/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic.simple import direct_to_template

from blogApp.users import forms
from blogApp.users.views import adminIntro


urlpatterns = patterns('',

    url(r'^admin/login/$', 'blogApp.users.views.login',
        kwargs={'authentication_form': forms.AuthenticationForm}, name="blog_login"),

    url(r'^admin/logout/$', 'django.contrib.auth.views.logout',
        kwargs={'next_page': '/'}, name="blog_logout"),

    url(r'^admin/register/$', 'blogApp.users.views.register', \
        kwargs={'form_class': forms.RegistrationForm}, name="blog_register"),

    url(r'^admin/disallowed/$', direct_to_template, \
        kwargs={'template': 'users/disallowed.html'}, name="registration_disallowed"),
    url(r'^admin/$', adminIntro.as_view(), name="admin_intro"),

)

urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns(
    '',
    (r'', include('blogApp.users.urls')),
    (r'', include('blogApp.posts.urls')),
)

blogApp/posts/models.py
import re
from google.appengine.ext import db

from blogApp.users.models import User


class Post(db.Model):
    title = db.StringProperty()
    intro = db.TextProperty()
    slug = db.StringProperty()
    content = db.TextProperty()
    last_edited = db.DateTimeProperty(auto_now=True)
    date_created = db.DateTimeProperty(auto_now_add=True)
    user = db.ReferenceProperty(User)
    published = db.BooleanProperty(default=False)
    date_published = db.DateTimeProperty()

    def formated_content(self):
        """translate multiple and single EOF signs
        to html tags"""
        if not self.content:
            return ""
        content = self.content.replace('\r', '')
        paragraphs = re.split('\n{2,}', content)
        paragraphs_joined = "</p><p>".join(paragraphs)
        paragraphs = "<p>" + paragraphs_joined + "</p>"

        lines = re.split('\n', paragraphs)
        lines_joined = "</br>".join(lines)
        return lines_joined

blogApp/posts/forms.py
import datetime
from django import forms
from blogApp.posts.models import Post


class PostForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 50, 'cols': 50}),
        required=False, help_text="Content of post. Separate paragras with at least 1 empty line.")
    title = forms.CharField(required=False, help_text="Title of post")
    slug = forms.SlugField(required=False,
        help_text="Slug for post, will be used in post url")
    intro = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'cols': 50}), \
        required=False, help_text="Introduction, first paragraph")
    public = forms.BooleanField(required=False, \
        help_text="Check it, if you want to publish post")
    next = forms.CharField(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        self.instance = kwargs.pop('instance')
        super(PostForm, self).__init__(*args, **kwargs)
        self.init_from_instance()

    def init_from_instance(self):
        if self.instance is not None:
            self.fields['title'].initial = self.instance.title
            self.fields['intro'].initial = self.instance.intro
            self.fields['slug'].initial = self.instance.slug
            self.fields['content'].initial = self.instance.content
            self.fields['public'].initial = self.instance.published

    def clean_slug(self):
        slug = self.cleaned_data.get('slug')
        if slug is not None:
            c = Post.all().filter('slug = ', slug).get()
            if c:
                if self.instance is None:
                    raise forms.ValidationError('Slug already taken')
                else:
                    if c.key() != self.instance.key():
                        raise forms.ValidationError('Slug already taken')

        return self.cleaned_data.get('slug')

    def clean(self):
        cleaned_data = super(PostForm, self).clean()
        public = cleaned_data.get("public")
        if public:
            content = cleaned_data.get('content')
            title = cleaned_data.get('title')
            intro = cleaned_data.get('intro')
            slug = cleaned_data.get('slug')

            if content is None or  title is None \
                or intro is None or slug is None:
                raise forms.ValidationError("If you want to publish article... everything required")

        return cleaned_data

    def save(self, commit=False):
        clean_d = self.cleaned_data
        if self.instance is None:
            self.instance = Post()
        self.instance.title = clean_d['title']
        self.instance.intro = clean_d['intro']
        self.instance.slug = clean_d['slug']
        self.instance.content = clean_d['content']
        if self.instance.user is None:
            self.instance.user = self.request.user

        if self.instance.published == False and clean_d['public'] \
            and not self.instance.date_published:
            self.instance.date_published = datetime.datetime.now()
        self.instance.published = clean_d['public']

        if commit:
            self.instance.put()

        return self.instance

blogApp/users/forms.py
# -*- coding: UTF-8 -*-


from django import forms
from django.contrib.auth import authenticate
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import PasswordResetForm


from blogApp.users.models import User, normalizeemail


attrs_dict = {'class': 'required'}


class EmailPasswordResetForm(PasswordResetForm):

    def clean_email(self):
        """
        Validates that a user exists with the given e-mail address.
        """
        email = self.cleaned_data["email"]
        self.user = None
        user = User.all().filter('email =', email).run(limit=1)
        if user:
            self.user = user[0]
        if self.user is None:
            raise forms.ValidationError(_("That e-mail address doesn't have an associated user account. Are you sure you've registered?"))
        return email


class AuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75,
                                                               placeholder="Type your e-mail address")),
                             label=_("Email address"))

    password = forms.CharField(widget=forms.PasswordInput(attrs=dict(attrs_dict,
                                                                placeholder='Type your password')),
                               label=_("Password"))

    def __init__(self, request=None, *args, **kwargs):
        """
        If request is passed in, the form will validate that cookies are
        enabled. Note that the request (a HttpRequest object) must have set a
        cookie with the key TEST_COOKIE_NAME and value TEST_COOKIE_VALUE before
        running this validation.
        """
        self.request = request
        self.user_cache = None
        super(AuthenticationForm, self).__init__(*args, **kwargs)

    def clean(self):

        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(email=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(_("Please enter a correct email and password."))

        # TODO: determine whether this should move to its own method.
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError(_("Your Web browser doesn't appear to have cookies enabled. Cookies are required for logging in."))
        return self.cleaned_data

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


class RegistrationForm(forms.Form):
    """ Form for registering a new user account.

    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.

    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend."""
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75,
                                                               placeholder="Type your e-mail address")),
                             label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(attrs_dict,
                                                                    placeholder="Type your password"),
                                render_value=False),
                                label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(attrs_dict,
                                                                    placeholder="Retype your password"),
                                render_value=False),
                                label=_("Password (again)"))

    def clean_email(self):
        email = normalizeemail(self.cleaned_data['email'])
        user = User.all().filter('email =', email).fetch(limit=1)
        if user:
            raise forms.ValidationError(_(u"This email address is already registered"))

        if email not in settings.ADMINS_EMAILS:
            raise forms.ValidationError(_(u"Can not register user with given email"))

        return self.cleaned_data['email']

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match. Note that an error here will end up in
        ``non_field_errors()`` because it doesn't apply to a single
        field.

        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields didn't match."))
        return self.cleaned_data

blogApp/posts/views.py
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie

from misc.paginator import create_paginator

from blogApp.posts.models import Post
from blogApp.posts.forms import PostForm

from blogApp.utils import json_response


class PostDashboard(TemplateView):

    @method_decorator(ensure_csrf_cookie)
    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        ctx = RequestContext(request)
        query = Post.all()

        paginator = create_paginator(request=request, query=query, \
            possible_ordering=["title", "published", "date_created", "last_edited"])

        ctx['paginator'] = paginator

        return render_to_response('posts/dashboard.html', {}, context_instance=ctx)


class MainPage(TemplateView):

    def get(self, request, *args, **kwargs):
        ctx = RequestContext(request)
        query = Post.all().filter('published = ', True).order('-date_published')

        paginator = create_paginator(request=request, query=query)

        ctx['paginator'] = paginator
        ctx['per_page'] = paginator.per_page

        return render_to_response('posts/main_page.html', {}, context_instance=ctx)


class ShowPost(TemplateView):

    def get(self, request, *args, **kwargs):
        post_slug = kwargs.get('post_slug')
        ctx = RequestContext(request)
        query = Post.all().filter('published = ', True).filter('slug = ', post_slug).fetch(1)
        if not query:
            raise Http404
        ctx['post'] = query[0]

        return render_to_response('posts/show_post.html', {}, context_instance=ctx)


class PreviewPost(TemplateView):

    def get(self, request, *args, **kwargs):
        post_key = kwargs.get('post_key')
        ctx = RequestContext(request)
        query = Post.get(post_key)
        if not query:
            raise Http404
        ctx['post'] = query

        return render_to_response('posts/show_post.html', {}, context_instance=ctx)


class NewPost(TemplateView):
    template_name = "posts/new_post.html"

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        form = PostForm(request=request, instance=None)
        ctx = RequestContext(request)
        ctx['form'] = form
        return render_to_response(self.template_name, {}, context_instance=ctx)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST, request=request, instance=None)
        if form.is_valid():
            post = form.save(commit=True)
            if post.title:
                msg = "Blog post %s have been created" % post.title
                msg += post.published and " and published" or "."
            else:
                msg = "New blog post have bee created."

            next = form.cleaned_data.get('next')
            if next == 'dashboard' or not next:
                messages.info(request, msg)
                return HttpResponseRedirect(reverse('post_dashboard'))
            if next == 'here':
                messages.info(request, msg)
                return HttpResponseRedirect(reverse('edit_post', kwargs={'post_key': str(post.key())}))
            if next == 'preview':
                return HttpResponseRedirect(reverse('preview_post', kwargs={'post_key': str(post.key())}))
        else:
            ctx = RequestContext(request)
            ctx['form'] = form

        return render_to_response(self.template_name, {}, context_instance=ctx)


class EditPost(TemplateView):
    template_name = "posts/edit_post.html"

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        key = kwargs.get('post_key')
        post = Post.get(key)
        if post is None:
            raise Http404
        form = PostForm(request=request, instance=post)
        ctx = RequestContext(request)
        ctx['form'] = form
        ctx['post'] = post
        return render_to_response(self.template_name, {}, context_instance=ctx)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        key = kwargs.get('post_key')
        post = Post.get(key)
        if post is None:
            raise Http404

        form = PostForm(request.POST, request=request, instance=post)
        if form.is_valid():
            post = form.save(commit=True)

            if post.title:
                msg = "Blog post %s have been edited" % post.title
                msg += post.published and " and published" or "."
            else:
                msg = "Blog post have been edited."

            next = form.cleaned_data.get('next')
            if next == 'dashboard' or not next:
                messages.info(request, msg)
                return HttpResponseRedirect(reverse('post_dashboard'))
            if next == 'here':
                messages.info(request, msg)
                return HttpResponseRedirect(reverse('edit_post', kwargs={'post_key': str(post.key())}))
            if next == 'preview':
                return HttpResponseRedirect(reverse('preview_post', kwargs={'post_key': str(post.key())}))
        else:
            ctx = RequestContext(request)
            ctx['form'] = form
            ctx['post'] = post
        return render_to_response(self.template_name, {}, context_instance=ctx)


@json_response
@login_required
def delete_post(request, post_key=None):
    if request.method != 'POST':
        return {'status': 'error', 'msg': 'only_post', 'code': 405}
    if post_key is None:
        return {'status': 'error', 'msg': 'post_id_not_provided', 'code': 400}

    post = Post.get(post_key)
    if post is None:
        return {'status': 'error', 'msg': 'post_not_found', 'code': 404}
    post.delete()
    return {'status': 'OK', 'msg': reverse('post_dashboard')}

blogApp/templates/posts/_post_form.html
<form class="form-horizontal well post_form" method="post" action="">
    {% if form.non_field_errors %}
        <div class="alert">{{form.non_field_errors}}</div>
    {% endif %}

    <fieldset>
        <legend>Content</legend>
        {% csrf_token %}
        <div class="control-group {%if form.title.errors%}error{%endif%}">
            {{ form.title.label_tag }}
            <div class="controls">
                <p class="help-block">
                    {{ form.title.help_text }}
                </p>
                {{ form.title }}
                <span class="help-inline">{{form.title.errors  }}</span>
            </div>

        </div>

        <div class="control-group {%if form.slug.errors%}error{%endif%}">

            {{ form.slug.label_tag }}
            <div class="controls">
                <p class="help-block">
                    {{ form.slug.help_text }}
                </p>
                {{ form.slug }}
                <span class="help-inline">{{ form.slug.errors }}</span>
            </div>
        </div>


        <div class="control-group {%if form.intro.errors%}error{%endif%}">
            {{ form.intro.label_tag }}
            <div class="controls">
                <p class="help-block">
                    {{ form.intro.help_text }}
                </p>
                {{ form.intro }}
                <span class="help-inline">{{ form.intro.errors }}</span>

            </div>
        </div>

        <div class="control-group {%if form.content.errors%}error{%endif%}">
            {{ form.content.label_tag }}
            <div class="controls">
                <p class="help-block">
                    {{ form.content.help_text }}
                </p>
                {{ form.content }}
                <span class="help-inline">{{ form.content.errors }}</span>

            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>Publication</legend>
        <div class="control-group {%if form.public.errors%}error{%endif%}">
            {{ form.public.label_tag }}
            <div class=public"controls">
                <p class="help-block">
                    {{ form.public.help_text }}
                </p>
                {{ form.public }}
                <span class="help-inline">{{form.public.errors  }}</span>

            </div>
        </div>
        {{form.next.as_hidden}}
    </fieldset>
    <div class="form-actions">
        <div class="pull-right">
            <input class="btn btn-primary btn-success to_dashboard" type="submit" value="{{button_value}}, go to dashboard" />
            <input class="btn btn-primary btn-info to_here" type="submit" value="{{button_value}}, stay here" />
            <input class="btn btn-primary to_preview" type="submit" value="{{button_value}}, go to preview" />
        </div>
    </div>
    <script type="text/javascript">
        $().ready(function(){
            $('.to_dashboard').click(function(e){
                $('.post_form').find('#id_next').val('dashboard');
            });
            $('.to_here').click(function(e){
                $('.post_form').find('#id_next').val('here');
            });
            $('.to_preview').click(function(e){
                $('.post_form').find('#id_next').val('preview');
            });

        });
    </script>
</form>

blogApp/templates/posts/dashboard.html
{% extends "base_admin.html"%}

{%load post_utils%}

{% block custom_javascript%}
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/jquery.cookie.js"></script>
    <script type="text/javascript">
        $().ready(function(){
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                        // Only send the token to relative URLs i.e. locally.
                        xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));
                    }
                }
            });

            remove_post_1 = function(e){
                e.preventDefault();
                var $button = $(e.target);
                $button.removeClass('stage1');
                $button.addClass('btn-danger');
                $button.html("Yes, I want to delete it");
                $button.off('click', remove_post_1);
                $button.on('click', remove_post_2);
            };
            remove_post_2 = function(e){
                e.preventDefault();
                var $button = $(e.target);
                var url = $button.attr('href');
                $.ajax({
                    type: "POST",
                    url: url,
                    success: function(resp){
                        if (resp.status == "OK"){
                            window.location.pathname = resp.msg;
                        }
                        else{
                            $button.parent().find(".removal_message").html(resp.msg);
                            $button.attr("disabled");
                            $button.off('click', remove_grid_2);
                        }
                    }

                })
            };

            $('.delete_post').on('click', remove_post_1);
        });
    </script>
{% endblock custom_javascript%}

{% block content%}

<div class="row">

    <div class="span11 offset1">

        {% if not paginator.objects%}
            <div class="no_posts_alert">
                No post found
            </div>
        {% else %}
            <div class="tabbable tabs-below">
                <div class="tab-content">
                    <table class="table table-striped table-grids">
                        <thead >
                            <tr class="dashboard_head">
                                <td class="id">
                                    No
                                </td>
                                <td class="title">
                                    <a class="dsc" href="{%url post_dashboard %}{% q_string order_by='-title' per_page=per_page%}">&darr;</a>
                                    <a class="asc" href="{%url post_dashboard %}{% q_string order_by='title' per_page=per_page%}">&uarr;</a>
                                    Post title
                                </td>
                                <td class="public">
                                    <a class="dsc" href="{%url post_dashboard %}{% q_string order_by='-published' per_page=per_page%}">&darr;</a>
                                    <a class="asc" href="{%url post_dashboard %}{% q_string order_by='published' per_page=per_page%}">&uarr;</a>
                                    Is published
                                </td>

                                <td class="date_published">
                                    <a class="dsc" href="{%url post_dashboard %}{% q_string order_by='-date_published' per_page=per_page%}">&darr;</a>
                                    <a class="asc" href="{%url post_dashboard %}{% q_string order_by='date_published' per_page=per_page%}">&uarr;</a>
                                    Published
                                </td>
                                <td class="date_edited">
                                    <a class="dsc" href="{%url post_dashboard %}{% q_string order_by='-last_edited' per_page=per_page%}">&darr;</a>
                                    <a class="asc" href="{%url post_dashboard %}{% q_string order_by='last_edited' per_page=per_page%}">&uarr;</a>
                                    Last Edited
                                </td>
                                <td>
                                    Actions
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for post in paginator.objects%}
                            <tr class="dashboard_line">
                                <td>{{forloop.counter|add:paginator.start}}</td>
                                <td>
                                    {%if post.published %}
                                        <a href= "{% url show_post post_slug=post.slug %}">{{post.title}}</a>
                                    {%else%}
                                        <a href= "{% url preview_post post_key=post.key|to_str%}">{{post.title}} (preview)</a>
                                    {%endif%}
                                </td>
                                <td>{% if post.published%}Yes{%else%}No{%endif%}</td>
                                <td>{{post.date_published|date:"M j, Y H:i"}}</td>
                                <td>{{post.last_edited|date:"M j, Y H:i"}}</td>

                                <td>
                                    <a href="{% url  edit_post post_key=post.key|to_str %}" class="btn btn-small btn-info">Edit</a>
                                    <a href="{% url  delete_post post_key=post.key|to_str %}" class="btn btn-small stage1 delete_post">Delete</a>
                                </td>
                            </tr>
                            {% endfor%}
                        </tbody>
                    </table>
                </div>
                {%if paginator.last_page > 0 and paginato.has_next%}

                    <div class="pagination pull-left">
                        Per page
                            <select class="input-mini">
                                <option value="10" {% if per_page == 10 %}selected="selected" {% endif%}>10</option>
                                <option value="20" {% if per_page == 20 %}selected="selected" {% endif%}>20</option>
                                <option value="50" {% if per_page == 50 %}selected="selected"{% endif%}>50</option>
                        </select>
                    </div>

                    <div class="pagination pull-right">

                        <ul>
                            {%if paginator.has_next%}
                                <li>
                                    <a class="button_page btn-next" href="{%url post_dashboard %}{% q_string page=paginator.last_page|add:1 order_by=order_by paginator_id=paginator.paginator_id per_page=per_page%}"></a>
                                </li>
                            {% endif%}
                            {%for p in paginator.last_page|get_range reversed %}
                                <li class="{%if p|add:1 == paginator.current_page%} active{%endif%}">
                                    <a class="button_page {% if forloop.first %}first{% endif %}" href="{%url post_dashboard %}{% q_string page=p|add:1 order_by=order_by paginator_id=paginator.paginator_id per_page=per_page%}"
                                    >
                                    {{p|add:1}}</a>
                                </li>
                            {% endfor%}
                        </ul>
                    </div>
                {%endif%}

            </div>
        {% endif%}
    </div>
</div>

{% endblock %}

blogApp/templates/posts/edit_post.html
{% extends "base_admin.html"%}
{% block title %}Edit post {{post.title}}{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="span12">

            <h3>Edit post</h3>

            {% include "posts/_post_form.html" with button_value="Edit" %}

        </div>

    </div>
</div>
{%endblock content%}

blogApp/templates/posts/main_page.html
{%extends "base_public.html"%}
{% load post_utils%}

{% block blog_content %}

    <div class="row">
        <div class="span6 offset3">
            {% if not paginator.objects %}
                <p>Sorry, no posts so far</p>
            {% else %}

                <div class='posts_list'>
                    {% for post in paginator.objects%}
                        <div class="post_entry">
                            <div class="post_entry_title">
                                <a href= "{% url show_post post_slug=post.slug %}">{{post.title}}</a>
                            </div>
                            <div class="post_entry_date">
                                {{post.date_published|date:"j F Y"}}
                            </div>
                        </div>
                    {% endfor%}
                </div>

                <div class="pagination">
                    <ul>
                    {%if paginator.last_page > 0 and paginator.has_next %}
                        {% for p in paginator.last_page|get_range %}
                            <li class="{% if p|add:1 == paginator.current_page %} active {% endif%}">
                                <a class="button_page" href="{%url main_page %}{% q_string page=p|add:1 paginator_id=paginator.paginator_id%}">
                                    {{p|add:1}}
                                </a>
                            </li>
                        {% endfor%}
                        {%if paginator.has_next%}
                            <li>
                                <a class="button_page btn-next" href="{%url main_page %}{% q_string page=paginator.last_page|add:1 paginator_id=paginator.paginator_id%}"></a>
                            </li>
                        {% endif%}
                    {% endif%}


                    </ul>
                <div class="pagination">

            {% endif%}

        </div>
    </div>
{% endblock blog_content%}

blogApp/templates/posts/new_post.html
{% extends "base_admin.html"%}
{% block title %}Create post{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="span12">

            <h3>Create post</h3>

            {% include "posts/_post_form.html" with button_value="Create" %}

        </div>

    </div>
</div>
{%endblock content%}